"""
Export Phase 2 Simplified (V1) model weights to a C header file.
=================================================================
Reads models/simplified/best_model.pth and normalization_params.pth
and writes deploy/model_weights.h — a standalone self-contained header
that can be compiled into the Bao hypervisor without any Python/PyTorch.

Usage:
    cd ~/github/IAES_Monitoring
    python3 scripts/export_model_c.py
"""

import torch
import numpy as np
import os

MODEL_PATH  = 'models/simplified/best_model.pth'
NORM_PATH   = 'models/simplified/normalization_params.pth'
OUT_PATH    = 'deploy/model_weights.h'

os.makedirs('deploy', exist_ok=True)

# ── Load ────────────────────────────────────────────────────────────────────────
print(f'Loading model   : {MODEL_PATH}')
print(f'Loading norm    : {NORM_PATH}')

state_dict = torch.load(MODEL_PATH, map_location='cpu', weights_only=False)
norm       = torch.load(NORM_PATH,  map_location='cpu', weights_only=False)

mean_np = np.array(norm['mean'], dtype=np.float32)
std_np  = np.array(norm['std'],  dtype=np.float32)
T       = float(norm.get('temp', 1.0))
W       = int(norm.get('w', 10))           # window size (fallback=10)

# MLP layer indices inside nn.Sequential:
# 0=Linear, 1=ReLU, 2=Dropout, 3=Linear, 4=ReLU, 5=Dropout, 6=Linear
W1 = state_dict['net.0.weight'].numpy()   # (16, 12)
B1 = state_dict['net.0.bias'].numpy()     # (16,)
W2 = state_dict['net.3.weight'].numpy()   # (16, 16)
B2 = state_dict['net.3.bias'].numpy()     # (16,)
W3 = state_dict['net.6.weight'].numpy()   # (1, 16)
B3 = state_dict['net.6.bias'].numpy()     # (1,)

N_IN  = W1.shape[1]   # 12
N_H1  = W1.shape[0]   # 16
N_H2  = W2.shape[0]   # 16
N_OUT = W3.shape[0]   # 1

print(f'Architecture    : {N_IN} → {N_H1} → {N_H2} → {N_OUT}')
print(f'Window size     : {W}')
print(f'Temperature     : {T:.6f}')
print(f'Norm features   : {len(mean_np)}')


# ── Format helpers ───────────────────────────────────────────────────────────────
def _fmt(v):
    """Format a float32 as a C literal (preserves sign, 8 significant digits)."""
    return f'{v:.8f}f'

def _array_1d(name, arr, type_='static const float'):
    n = len(arr)
    vals = ', '.join(_fmt(v) for v in arr)
    return f'{type_} {name}[{n}] = {{\n    {vals}\n}};\n'

def _array_2d(name, arr, type_='static const float'):
    rows, cols = arr.shape
    lines = []
    for r in range(rows):
        row_str = ', '.join(_fmt(v) for v in arr[r])
        lines.append(f'    /* [{r}] */ {{ {row_str} }}')
    body = ',\n'.join(lines)
    return f'{type_} {name}[{rows}][{cols}] = {{\n{body}\n}};\n'


# ── Write header ─────────────────────────────────────────────────────────────────
lines = []
lines.append('/* ================================================================')
lines.append(' * model_weights.h  —  AUTO-GENERATED by scripts/export_model_c.py')
lines.append(' * DO NOT EDIT MANUALLY.')
lines.append(' *')
lines.append(' * Model   : Phase 2 Simplified V1 MLP')
lines.append(f' * Arch    : Linear({N_IN}→{N_H1}) → ReLU → Linear({N_H1}→{N_H2}) → ReLU → Linear({N_H2}→{N_OUT})')
lines.append(f' * Params  : {W1.size + B1.size + W2.size + B2.size + W3.size + B3.size}')
lines.append(f' * Window  : W = {W} samples')
lines.append(f' * Features: IPC, MPKI, L2_PRESSURE, BRANCH_MISS_RATE × {{mean, std, delta}}')
lines.append(f' * Temp    : T = {T:.6f}  (calibration temperature)')
lines.append(f' * Thresh  : tau = 0.50  (recommended; see best_model_classification.md)')
lines.append(' * ================================================================')
lines.append(' */')
lines.append('')
lines.append('#ifndef MODEL_WEIGHTS_H')
lines.append('#define MODEL_WEIGHTS_H')
lines.append('')
lines.append(f'#define MDL_N_FEATURES  {N_IN}')
lines.append(f'#define MDL_N_H1        {N_H1}')
lines.append(f'#define MDL_N_H2        {N_H2}')
lines.append(f'#define MDL_N_OUT       {N_OUT}')
lines.append(f'#define MDL_WINDOW_SIZE {W}')
lines.append(f'#define MDL_TEMPERATURE {_fmt(T)}')
lines.append(f'#define MDL_THRESHOLD   0.50000000f')
lines.append('')
lines.append('/* ── Feature normalisation (z-score: subtract mean, divide by std) ── */')
lines.append(_array_1d('MDL_FEAT_MEAN', mean_np))
lines.append(_array_1d('MDL_FEAT_STD',  std_np))
lines.append('/* ── Layer 1 : Linear({:d} → {:d}) ─────────────────────────────────── */'.format(N_IN, N_H1))
lines.append(_array_2d('MDL_W1', W1))
lines.append(_array_1d('MDL_B1', B1))
lines.append('/* ── Layer 2 : Linear({:d} → {:d}) ─────────────────────────────────── */'.format(N_H1, N_H2))
lines.append(_array_2d('MDL_W2', W2))
lines.append(_array_1d('MDL_B2', B2))
lines.append('/* ── Output  : Linear({:d} → {:d}) ──────────────────────────────────── */'.format(N_H2, N_OUT))
lines.append(_array_2d('MDL_W3', W3))
lines.append(_array_1d('MDL_B3', B3))
lines.append('#endif /* MODEL_WEIGHTS_H */')

with open(OUT_PATH, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f'\nHeader written  : {OUT_PATH}')
print(f'  {W1.size + B1.size + W2.size + B2.size + W3.size + B3.size} weight/bias values total')
print('Done.')
